/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaactivityexcercise;

/**
 *
 * @author Isaac Ogunleye
 */
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class DemoCalc extends javax.swing.JFrame {

    /**
     * Creates new form DemoCalc
     */
    public DemoCalc() {
        initComponents();

        this.setResizable(false);
        this.setTitle("Aizik Demo Calc");
        this.setLocationRelativeTo(null);

        ResScreen.setFocusable(false);
        ResScreen.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtfNum1 = new javax.swing.JTextField();
        jtfNum2 = new javax.swing.JTextField();
        ResScreen = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        divBtn = new javax.swing.JButton();
        multBtn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 157, 95));

        jtfNum1.setBackground(new java.awt.Color(255, 255, 255));
        jtfNum1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jtfNum1.setForeground(new java.awt.Color(0, 0, 0));
        jtfNum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNum1.setToolTipText("Enter integer input here");
        jtfNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNum1ActionPerformed(evt);
            }
        });
        jtfNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNum1KeyTyped(evt);
            }
        });

        jtfNum2.setBackground(new java.awt.Color(255, 255, 255));
        jtfNum2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jtfNum2.setForeground(new java.awt.Color(0, 0, 0));
        jtfNum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNum2.setToolTipText("Enter integer input here");
        jtfNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfNum2KeyTyped(evt);
            }
        });

        ResScreen.setBackground(new java.awt.Color(0, 0, 0));
        ResScreen.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        ResScreen.setForeground(new java.awt.Color(255, 255, 255));
        ResScreen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ResScreen.setToolTipText("Result displayed here");

        addBtn.setBackground(new java.awt.Color(0, 0, 0));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("ADDITION");
        addBtn.setToolTipText("Add");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        divBtn.setBackground(new java.awt.Color(0, 0, 0));
        divBtn.setForeground(new java.awt.Color(255, 255, 255));
        divBtn.setText("DIVISION");
        divBtn.setToolTipText("Divide");
        divBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divBtnActionPerformed(evt);
            }
        });

        multBtn.setBackground(new java.awt.Color(0, 0, 0));
        multBtn.setForeground(new java.awt.Color(255, 255, 255));
        multBtn.setText("MULTIPLICATION");
        multBtn.setToolTipText("Multiply");
        multBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multBtnActionPerformed(evt);
            }
        });

        subBtn.setBackground(new java.awt.Color(0, 0, 0));
        subBtn.setForeground(new java.awt.Color(255, 255, 255));
        subBtn.setText("SUBTRACTION");
        subBtn.setToolTipText("Subtract");
        subBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_Close_Window_48px.png"))); // NOI18N
        jLabel1.setToolTipText("Close");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/icons8_Minimize_Window_48px.png"))); // NOI18N
        jLabel2.setToolTipText("Minimize");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResScreen)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(multBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addGap(93, 93, 93))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(divBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfNum2)
                            .addComponent(subBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(subBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNum1ActionPerformed

    }//GEN-LAST:event_jtfNum1ActionPerformed

    private void jtfNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNum1KeyTyped
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            jtfNum1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        } else {
            evt.consume();
            jtfNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        }

        if (evt.getKeyChar() == com.sun.glass.events.KeyEvent.VK_BACKSPACE) {
            jtfNum1.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        }
    }//GEN-LAST:event_jtfNum1KeyTyped

    private void jtfNum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNum2KeyTyped
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            jtfNum2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        } else {
            evt.consume();
            jtfNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
        }

        if (evt.getKeyChar() == com.sun.glass.events.KeyEvent.VK_BACKSPACE) {
            jtfNum2.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        }
    }//GEN-LAST:event_jtfNum2KeyTyped

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        int response = JOptionPane.showConfirmDialog(null, "Are u sure u want to close the App?", "Close App", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {
            return;
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        if ((jtfNum1.getText().equals("")) || (jtfNum2.getText().equals(""))) {
//           
            JOptionPane.showMessageDialog(null, "The input fields cannot be empty!", "Error Message!", JOptionPane.ERROR_MESSAGE);
            if (jtfNum1.getText().equals("")) {
                jtfNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            }
            if ((jtfNum2.getText().equals(""))) {
                jtfNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            }
        } else {

            int firstIn = Integer.parseInt(jtfNum1.getText());
            int secondIn = Integer.parseInt(jtfNum2.getText());
            int sum = firstIn + secondIn;
            String total = Integer.toString(sum);

            ResScreen.setText(total);
            jtfNum1.setText("");
            jtfNum2.setText("");

        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
          if ((jtfNum1.getText().equals("")) || (jtfNum2.getText().equals(""))) {
//           
            JOptionPane.showMessageDialog(null, "The input fields cannot be empty!", "Error Message!", JOptionPane.ERROR_MESSAGE);
            if (jtfNum1.getText().equals("")) {
                jtfNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            }
            if ((jtfNum2.getText().equals(""))) {
                jtfNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            }
        } else {

            int firstIn = Integer.parseInt(jtfNum1.getText());
            int secondIn = Integer.parseInt(jtfNum2.getText());
            int sub = firstIn - secondIn;
            String total = Integer.toString(sub);

            ResScreen.setText(total);
            jtfNum1.setText("");
            jtfNum2.setText("");

        }
    }//GEN-LAST:event_subBtnActionPerformed

    private void multBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multBtnActionPerformed
          if ((jtfNum1.getText().equals("")) || (jtfNum2.getText().equals(""))) {
//           
            JOptionPane.showMessageDialog(null, "The input fields cannot be empty!", "Error Message!", JOptionPane.ERROR_MESSAGE);
            if (jtfNum1.getText().equals("")) {
                jtfNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            }
            if ((jtfNum2.getText().equals(""))) {
                jtfNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            }
        } else {

            int firstIn = Integer.parseInt(jtfNum1.getText());
            int secondIn = Integer.parseInt(jtfNum2.getText());
            int sum = firstIn * secondIn;
            String total = Integer.toString(sum);

            ResScreen.setText(total);
            jtfNum1.setText("");
            jtfNum2.setText("");

        }
    }//GEN-LAST:event_multBtnActionPerformed

    private void divBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divBtnActionPerformed
          if ((jtfNum1.getText().equals("")) || (jtfNum2.getText().equals(""))) {
//           
            JOptionPane.showMessageDialog(null, "The input fields cannot be empty!", "Error Message!", JOptionPane.ERROR_MESSAGE);
            if (jtfNum1.getText().equals("")) {
                jtfNum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            }
            if ((jtfNum2.getText().equals(""))) {
                jtfNum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            }
        } else {

            double firstIn = Double.parseDouble(jtfNum1.getText());
            double secondIn = Double.parseDouble(jtfNum2.getText());
            double sum =  firstIn / secondIn;
            String total = Double.toString(sum);

            ResScreen.setText(total);
            jtfNum1.setText("");
            jtfNum2.setText("");

        }
    }//GEN-LAST:event_divBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ResScreen;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton divBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfNum1;
    private javax.swing.JTextField jtfNum2;
    private javax.swing.JButton multBtn;
    private javax.swing.JButton subBtn;
    // End of variables declaration//GEN-END:variables
}
